# Generated by Django 3.0.8 on 2020-07-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_innaugration', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('team_lead_id', models.CharField(blank=True, max_length=15, null=True)),
                ('average_pay', models.CharField(blank=True, max_length=10, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='objectives_dashboard.Department')),
            ],
            options={
                'db_table': 'teams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='objectives_dashboard.Teams')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('objective_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('objective_text', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='objectives_dashboard.Users')),
            ],
            options={
                'db_table': 'objectives',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Keyresults',
            fields=[
                ('keyresult_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=12, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='objectives_dashboard.Objectives')),
            ],
            options={
                'db_table': 'keyresults',
                'managed': True,
            },
        ),
    ]
