# Generated by Django 3.0.8 on 2020-07-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyresults',
            name='keyresult_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='objective_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
